name: thorin
favicon: null
layout_spectrum: 0.8473650927189738
typography_spectrum: 0.8954628605861217
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.014038147637620568
  lightness: 0.7676317987497896
  saturation: 0.7954678935930133
  rhythmicContrast: 0.5802818110678345
purpose: []
